name: sqflite_entities
description: Simple entity project without code generation.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  sqflite: ^2.4.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
  sqflite_common_ffi: ^2.3.7

flutter:
